### ISSUE TITLE
发送消息后，没有报错，但是手机始终是收不到

### ISSUE THREAD

**Issue by AlexZhangrj** [teaey/apns4j#17]
Java端发送消息后，没有报错，但是手机始终是收不到：
我的代码如下：
ApnsChannelFactory apnsChannelFactory = Apns4j.newChannelFactoryBuilder()
				.keyStoreMeta(certPath)
				.keyStorePwd("Rj1234567890")
				.keyStoreType(KeyStoreType.PKCS12)
				.apnsGateway(ApnsGateway.PRODUCTION)
				.build();
		//Setp 2
		ApnsChannel apnsChannel = apnsChannelFactory.newChannel();
		//Step 3 create & init notify payload
		ApnsPayload apnsPayload = Apns4j.newPayload()
		        .alertTitle("Up Task消息")
		        .alertBody(message)
		        .sound("default");
		//Step 4 send via channel
		apnsChannel.send(token.getApnsToken().replace("<", "").replace(" ", "").replace(">", ""), apnsPayload);
		//Step 5 in the end, apnsChannel can be Recycle and Reuse
		apnsChannel.close();
		log.debug("sendApnsMessage end");

**Comment by teaey** [comment]
有报什么错误吗？

在 2019-07-01 13:35:12，"AlexZhangrj" <notifications@github.com> 写道：


Java端发送消息后，没有报错，但是手机始终是收不到：
我的代码如下：
ApnsChannelFactory apnsChannelFactory = Apns4j.newChannelFactoryBuilder()
.keyStoreMeta(certPath)
.keyStorePwd("Rj1234567890")
.keyStoreType(KeyStoreType.PKCS12)
.apnsGateway(ApnsGateway.PRODUCTION)
.build();
//Setp 2
ApnsChannel apnsChannel = apnsChannelFactory.newChannel();
//Step 3 create & init notify payload
ApnsPayload apnsPayload = Apns4j.newPayload()
.alertTitle("Up Task消息")
.alertBody(message)
.sound("default");
//Step 4 send via channel
apnsChannel.send(token.getApnsToken().replace("<", "").replace(" ", "").replace(">", ""), apnsPayload);
//Step 5 in the end, apnsChannel can be Recycle and Reuse
apnsChannel.close();
log.debug("sendApnsMessage end");

**Comment by AlexZhangrj** [comment]
问题解决了，我的代码的问题
